training_pipeline_config:
  pipeline_name: src
  artifact_dir: artifact

data_ingestion_config:
  data_ingestion_artifact_dir: data_ingestion_artifact
  raw_data_dir: raw_data_dir
  ingested_dir: ingested_dir
  ingested_train_dir: ingested_train_dir
  ingested_test_dir: ingested_test_dir
  collection_name: us-visa-collection
  train_test_split_ratio: 0.2

data_validation_config:
  data_validation_artifact_dir: data_validation_artifact
  report_dir: drift_report_directory
  report_file_name: report.yaml

data_transformation_config:
  data_transformation_artifact_dir: data_transformation_artifact
  transformed_dir: transformed_dir
  transformed_train_file_name: transformed_train_data.npy
  transformed_test_file_name: transformed_test_data.npy
  preprocessed_dir: processed_dir
  preprocessed_object_file_name: preprocessing.pkl

model_trainer_config:
  trained_model_dir: trained_model
  model_file_name: model.pkl
  base_accuracy: 0.6
  model_config_dir: config
  model_config_file_name: train.yaml

model_evaluation_config:
  changed_threshold_score: 0.02
  bucket_name: visapredictionsproject2024june
  s3_model_key_path: model.pkl

model_pusher_config:
  bucket_name: visapredictionsproject2024june
  s3_model_key_path: model.pkl
