grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 3
    n_jobs: -1
model_selection:
  module_1:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
        n_estimators: 50
        max_samples: 0.75
    search_param_grid:
        max_features:
        - 0.75
        max_samples:
        - 0.5
        - 0.76
        - 1.0
        n_estimators:     
        - 75
        - 100